baseURL: https://anirban-portfolio-dsb.netlify.app/
languageCode: en-us
title: Portfolio website for Anirban Mukhopadhyay
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: My projects
    title: Hi, my name is Anirban Mukhopadhyay and I am an MBA student at LBS
  blog: {}
  contact:
    address:  
      - city: London, NW15AF
        country: United Kingdom
        street: Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: muk.anirban123@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (44) 7442645127 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    # copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/heisenbergiitd/
      - icon: fa-facebook
        label: Facebook
        url: https://facebook.com/anirban261/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/muk_anirban/
      - icon: fa-github
        label: GitHub
        url: https://github.com/muk-anirban
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/anirban261/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Anirban
    title: Portfolio
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: London Business School
        title: London Business School
        url: blogs/lbs
      - image: Donation by Political Party.jpg
        subtitle: Donations by Political Party
        title: Donation Trends
        url: blogs/donations
      - image: Bechdel Test 1.jpg
        subtitle: Movies passing the Bechdel Test
        title: Bechdel test
        url: blogs/bechdel
      - image: Decision Tree Metascore.jpg
        subtitle: Decision Tree by Metascore
        title: Metascore
        url: blogs/metascore
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Anirban is a first year MBA student at London Business School. He started his career as a Consultant but soon switched to a Private Equity Portfolio Company, where he worked as Chief of Staff. He is now looking to move back to consulting."
    title: About Anirban
    url: blogs
markup: 
  goldmark: 
    renderer: 
      unsafe: true